"""initial_schema

Revision ID: 879b51a6e362
Revises: 
Create Date: 2026-01-16 09:10:42.034632

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '879b51a6e362'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('environment_variables',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('scope', sa.Enum('PROJECT', 'ENVIRONMENT', 'SERVICE', name='variablescope'), nullable=False),
    sa.Column('resource_id', sa.String(), nullable=False),
    sa.Column('key', sa.String(), nullable=False),
    sa.Column('value', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_environment_variables_deleted_at'), 'environment_variables', ['deleted_at'], unique=False)
    op.create_index(op.f('ix_environment_variables_key'), 'environment_variables', ['key'], unique=False)
    op.create_index(op.f('ix_environment_variables_resource_id'), 'environment_variables', ['resource_id'], unique=False)
    op.create_index(op.f('ix_environment_variables_scope'), 'environment_variables', ['scope'], unique=False)
    op.create_table('oauth_states',
    sa.Column('state', sa.String(), nullable=False),
    sa.Column('redirect_uri', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('state')
    )
    op.create_index(op.f('ix_oauth_states_created_at'), 'oauth_states', ['created_at'], unique=False)
    op.create_index(op.f('ix_oauth_states_state'), 'oauth_states', ['state'], unique=False)
    op.create_table('permissions',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('action', sa.Enum('READ', 'WRITE', 'DELETE', 'ADMIN', name='permissionaction'), nullable=False),
    sa.Column('resource', sa.Enum('PROJECT', 'ENVIRONMENT', 'SERVICE', 'CONFIG', 'USER', 'PERMISSION', name='permissionresource'), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_permissions_name'), 'permissions', ['name'], unique=True)
    op.create_table('secrets',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('scope', sa.Enum('PROJECT', 'ENVIRONMENT', 'SERVICE', name='variablescope'), nullable=False),
    sa.Column('resource_id', sa.String(), nullable=False),
    sa.Column('key', sa.String(), nullable=False),
    sa.Column('value', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_secrets_deleted_at'), 'secrets', ['deleted_at'], unique=False)
    op.create_index(op.f('ix_secrets_key'), 'secrets', ['key'], unique=False)
    op.create_index(op.f('ix_secrets_resource_id'), 'secrets', ['resource_id'], unique=False)
    op.create_index(op.f('ix_secrets_scope'), 'secrets', ['scope'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_admin', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_deleted_at'), 'users', ['deleted_at'], unique=False)
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('projects',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('owner_id', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name', name='uq_project_name')
    )
    op.create_index(op.f('ix_projects_deleted_at'), 'projects', ['deleted_at'], unique=False)
    op.create_index(op.f('ix_projects_name'), 'projects', ['name'], unique=False)
    op.create_table('resource_permissions',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('scope', postgresql.ENUM('project', 'environment', 'service', name='permissionscope'), nullable=False),
    sa.Column('resource_id', sa.String(), nullable=False),
    sa.Column('actions', sa.JSON(), nullable=False),
    sa.Column('granted_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('granted_by', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['granted_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'scope', 'resource_id', name='uq_user_resource_permission')
    )
    op.create_index(op.f('ix_resource_permissions_resource_id'), 'resource_permissions', ['resource_id'], unique=False)
    op.create_index(op.f('ix_resource_permissions_scope'), 'resource_permissions', ['scope'], unique=False)
    op.create_index(op.f('ix_resource_permissions_user_id'), 'resource_permissions', ['user_id'], unique=False)
    op.create_table('user_permissions',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('permission_id', sa.String(), nullable=False),
    sa.Column('resource_id', sa.String(), nullable=True),
    sa.Column('granted_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('granted_by', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['granted_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['permission_id'], ['permissions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'permission_id', 'resource_id', name='uq_user_permission_resource')
    )
    op.create_index(op.f('ix_user_permissions_permission_id'), 'user_permissions', ['permission_id'], unique=False)
    op.create_index(op.f('ix_user_permissions_resource_id'), 'user_permissions', ['resource_id'], unique=False)
    op.create_index(op.f('ix_user_permissions_user_id'), 'user_permissions', ['user_id'], unique=False)
    # Create environmenttype enum if it doesn't exist
    conn = op.get_bind()
    result = conn.execute(sa.text("SELECT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'environmenttype')"))
    enum_exists = result.scalar()
    
    if not enum_exists:
        op.execute("CREATE TYPE environmenttype AS ENUM ('development', 'testing', 'staging', 'production', 'sandbox', 'dev', 'prod')")
    
    op.create_table('environments',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('type', postgresql.ENUM('development', 'testing', 'staging', 'production', 'sandbox', 'dev', 'prod', name='environmenttype', create_type=False), nullable=False),
    sa.Column('url', sa.String(), nullable=True),
    sa.Column('project_id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name', 'project_id', name='uq_environment_name_project')
    )
    op.create_index(op.f('ix_environments_deleted_at'), 'environments', ['deleted_at'], unique=False)
    op.create_index(op.f('ix_environments_name'), 'environments', ['name'], unique=False)
    op.create_index(op.f('ix_environments_project_id'), 'environments', ['project_id'], unique=False)
    op.create_index(op.f('ix_environments_type'), 'environments', ['type'], unique=False)
    op.create_table('project_configs',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('project_id', sa.String(), nullable=False),
    sa.Column('key', sa.String(), nullable=False),
    sa.Column('value', sa.Text(), nullable=True),
    sa.Column('config_data', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('project_id', 'key', name='uq_project_config_key')
    )
    op.create_index(op.f('ix_project_configs_deleted_at'), 'project_configs', ['deleted_at'], unique=False)
    op.create_index(op.f('ix_project_configs_key'), 'project_configs', ['key'], unique=False)
    op.create_index(op.f('ix_project_configs_project_id'), 'project_configs', ['project_id'], unique=False)
    op.create_table('services',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('type', sa.Enum('MICROSERVICE', 'WEBAPP', 'DATABASE', 'QUEUE', name='servicetype'), nullable=False),
    sa.Column('project_id', sa.String(), nullable=False),
    sa.Column('owner', sa.String(), nullable=True),
    sa.Column('repo', sa.String(), nullable=True),
    sa.Column('runtime', sa.String(), nullable=True),
    sa.Column('status', sa.Enum('HEALTHY', 'DEGRADED', 'DOWN', 'UNKNOWN', name='servicestatus'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name', 'project_id', name='uq_service_name_project')
    )
    op.create_index(op.f('ix_services_deleted_at'), 'services', ['deleted_at'], unique=False)
    op.create_index(op.f('ix_services_name'), 'services', ['name'], unique=False)
    op.create_index(op.f('ix_services_project_id'), 'services', ['project_id'], unique=False)
    op.create_index(op.f('ix_services_status'), 'services', ['status'], unique=False)
    op.create_index(op.f('ix_services_type'), 'services', ['type'], unique=False)
    op.create_table('environment_configs',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('environment_id', sa.String(), nullable=False),
    sa.Column('key', sa.String(), nullable=False),
    sa.Column('value', sa.Text(), nullable=True),
    sa.Column('config_data', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['environment_id'], ['environments.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('environment_id', 'key', name='uq_environment_config_key')
    )
    op.create_index(op.f('ix_environment_configs_deleted_at'), 'environment_configs', ['deleted_at'], unique=False)
    op.create_index(op.f('ix_environment_configs_environment_id'), 'environment_configs', ['environment_id'], unique=False)
    op.create_index(op.f('ix_environment_configs_key'), 'environment_configs', ['key'], unique=False)
    op.create_table('service_configs',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('service_id', sa.String(), nullable=False),
    sa.Column('key', sa.String(), nullable=False),
    sa.Column('value', sa.Text(), nullable=True),
    sa.Column('config_data', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['service_id'], ['services.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('service_id', 'key', name='uq_service_config_key')
    )
    op.create_index(op.f('ix_service_configs_deleted_at'), 'service_configs', ['deleted_at'], unique=False)
    op.create_index(op.f('ix_service_configs_key'), 'service_configs', ['key'], unique=False)
    op.create_index(op.f('ix_service_configs_service_id'), 'service_configs', ['service_id'], unique=False)
    op.create_table('service_environments',
    sa.Column('service_id', sa.String(), nullable=False),
    sa.Column('environment_id', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['environment_id'], ['environments.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['service_id'], ['services.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('service_id', 'environment_id')
    )
    op.create_index('ix_service_environments_service_id', 'service_environments', ['service_id'], unique=False)
    op.create_index('ix_service_environments_environment_id', 'service_environments', ['environment_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_service_environments_environment_id', table_name='service_environments')
    op.drop_index('ix_service_environments_service_id', table_name='service_environments')
    op.drop_table('service_environments')
    op.drop_index(op.f('ix_service_configs_service_id'), table_name='service_configs')
    op.drop_index(op.f('ix_service_configs_key'), table_name='service_configs')
    op.drop_index(op.f('ix_service_configs_deleted_at'), table_name='service_configs')
    op.drop_table('service_configs')
    op.drop_index(op.f('ix_environment_configs_key'), table_name='environment_configs')
    op.drop_index(op.f('ix_environment_configs_environment_id'), table_name='environment_configs')
    op.drop_index(op.f('ix_environment_configs_deleted_at'), table_name='environment_configs')
    op.drop_table('environment_configs')
    op.drop_index(op.f('ix_services_type'), table_name='services')
    op.drop_index(op.f('ix_services_status'), table_name='services')
    op.drop_index(op.f('ix_services_project_id'), table_name='services')
    op.drop_index(op.f('ix_services_name'), table_name='services')
    op.drop_index(op.f('ix_services_deleted_at'), table_name='services')
    op.drop_table('services')
    op.drop_index(op.f('ix_project_configs_project_id'), table_name='project_configs')
    op.drop_index(op.f('ix_project_configs_key'), table_name='project_configs')
    op.drop_index(op.f('ix_project_configs_deleted_at'), table_name='project_configs')
    op.drop_table('project_configs')
    op.drop_index(op.f('ix_environments_type'), table_name='environments')
    op.drop_index(op.f('ix_environments_project_id'), table_name='environments')
    op.drop_index(op.f('ix_environments_name'), table_name='environments')
    op.drop_index(op.f('ix_environments_deleted_at'), table_name='environments')
    op.drop_table('environments')
    # Drop environmenttype enum if it exists
    conn = op.get_bind()
    result = conn.execute(sa.text("SELECT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'environmenttype')"))
    if result.scalar():
        op.execute("DROP TYPE environmenttype")
    op.drop_index(op.f('ix_user_permissions_user_id'), table_name='user_permissions')
    op.drop_index(op.f('ix_user_permissions_resource_id'), table_name='user_permissions')
    op.drop_index(op.f('ix_user_permissions_permission_id'), table_name='user_permissions')
    op.drop_table('user_permissions')
    op.drop_index(op.f('ix_resource_permissions_user_id'), table_name='resource_permissions')
    op.drop_index(op.f('ix_resource_permissions_scope'), table_name='resource_permissions')
    op.drop_index(op.f('ix_resource_permissions_resource_id'), table_name='resource_permissions')
    op.drop_table('resource_permissions')
    op.drop_index(op.f('ix_projects_name'), table_name='projects')
    op.drop_index(op.f('ix_projects_deleted_at'), table_name='projects')
    op.drop_table('projects')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_index(op.f('ix_users_deleted_at'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_secrets_scope'), table_name='secrets')
    op.drop_index(op.f('ix_secrets_resource_id'), table_name='secrets')
    op.drop_index(op.f('ix_secrets_key'), table_name='secrets')
    op.drop_index(op.f('ix_secrets_deleted_at'), table_name='secrets')
    op.drop_table('secrets')
    op.drop_index(op.f('ix_permissions_name'), table_name='permissions')
    op.drop_table('permissions')
    op.drop_index(op.f('ix_oauth_states_state'), table_name='oauth_states')
    op.drop_index(op.f('ix_oauth_states_created_at'), table_name='oauth_states')
    op.drop_table('oauth_states')
    op.drop_index(op.f('ix_environment_variables_scope'), table_name='environment_variables')
    op.drop_index(op.f('ix_environment_variables_resource_id'), table_name='environment_variables')
    op.drop_index(op.f('ix_environment_variables_key'), table_name='environment_variables')
    op.drop_index(op.f('ix_environment_variables_deleted_at'), table_name='environment_variables')
    op.drop_table('environment_variables')
    # ### end Alembic commands ###
